spring:
  profiles:
    active: test-rabbitmq-postgresql
---
spring:
  config:
    activate:
      on-profile: test-rabbitmq-postgresql
  datasource:
    url: jdbc:postgresql://localhost:35432/postgres
    username: postgres
    password: 1111

    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  rabbitmq:
    host: b-2e677b4d-6a2e-4e58-b6ba-95f8e1738a5d.mq.ap-northeast-2.amazonaws.com
    port: 5671
    username: mqadmin
    password: mqadmin1234!@#$
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: manual